version: "3.8"
services:
  eureka-server:
    build: ./movie-service-registry
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - APPLICATION_NAME=movie-services-registry
      - REGISTER_WITH_EUREKA=false
      - FETCH_REGISTRY=false
  api-gateway:
    build: ./api-gateway
    ports:
        - "8009:8765"
    environment:
      - SERVER_PORT=8765
      - APPLICATION_NAME=api-gateway
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://eureka-server:8761/eureka/
  booking-service:
    build: ./booking-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - APPLICATION_NAME=booking-service
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://eureka-server:8761/eureka/
  payment-service:
    build: ./payment-service
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - APPLICATION_NAME=payment-service
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://eureka-server:8761/eureka/
  notification-service:
    build: ./notification-service
    ports:
      - "7070:7070"
    environment:
      - SERVER_PORT=7070
      - APPLICATION_NAME=notification-service
      - REGISTER_WITH_EUREKA=true
      - DEFAULT_ZONE=http://eureka-server:8761/eureka/



