server:
 port: ${SERVER_PORT:9090}
spring:
 application:
  name: ${APPLICATION_NAME:payment-service}
 datasource:
  url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:payments?createDatabaseIfNotExist=true}
  username: ${MYSQL_USER:root}
  # password: ${MYSQL_PASSWORD:}
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
eureka:
  client:
   register-with-eureka: ${REGISTER_WITH_EUREKA:true}
   service-url:
    defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
management:
 endpoints:
  web:
   exposure:
    include: "*"
 health:
  liveness-state:
   enabled: true
  #It makes sure spring boot app always up and running,
  #gincase of db failure(ready to take traffic)
  readiness-state:
   enabled: true
  #it checks if ready to take requests
 endpoint:
   health:
    probes:
     enabled: true
stripe:
 key: