server:
  port: ${SERVER_PORT:8765}
spring:
  application:
    name: ${APPLICATION_NAME:api-gateway}
  cloud:
    gateway:
      routes:
       - id: bookings-route
         uri: lb://booking-service
         predicates:
              - Path=/bookings/**
         filters:
           - name: CircuitBreaker
             args:
               name: bookings-route
               fallbackUrl: forward:/booking-fallback
eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    #It makes sure spring boot app always up and running,
    #incaseof db failure(ready to take traffic)
    readiness-state:
      enabled: true
  #it checks if ready to take requests
  endpoint:
    health:
      probes:
        enabled: true
